# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

     working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Install Bundler
          command: gem install bundler:2.0.1
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Install Firebase Tools
          command: sudo npm install -g firebase-tools
      - run:
          name: Build Jekyll Site
          command: bundle exec jekyll build
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master